tokenizer:
  vocab_size: 32000
  min_freq: 2
  special_tokens:
    - "<pad>"
    - "<bos>"
    - "<eos>"
    - "<unk>"

model:
  vocab_size: 32000
  d_model: 768
  n_heads: 12
  n_layers: 6
  d_ff: 3072
  max_seq_len: 512
  dropout: 0.1

training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_steps: 1000
  gradient_clip_val: 1.0
  gradient_accumulation_steps: 1
  eval_steps: 100
  save_steps: 1000
  logging_steps: 10
  checkpoint_dir: "checkpoints"

data:
  val_split: 0.1

logging:
  log_dir: "logs" 